package com.modernjava.record;

import java.math.BigDecimal;

public record Product(String name,
                      BigDecimal cost,
                      String type) {

    //By default, the constructors that are generated by the compiler are called canonical constructor.
    public Product {
        System.out.println("Inside the validation block");
        if (name!=null && name.isBlank()) {
            throw new IllegalArgumentException("name value is not valid!");
        }

        if (cost.compareTo(BigDecimal.ZERO) <= 0) {
            throw new IllegalArgumentException("cost value is not valid!");
        }
    }

    public Product(String name, BigDecimal cost) {

        this(name, cost, "GENERAL");
    }
}
